CREATE DATABASE [DBACentral]
ON PRIMARY
( 
	name			= DBACentral_Data
	,FILENAME		= 'D:\SQLData\Default\DBACentral_Data.mdf'
	,SIZE			= 1 GB
	,MAXSIZE		= UNLIMITED
	,FILEGROWTH		= 512 MB
)
,FILEGROUP History
(
	name			= DBACentral_History_Data
	,FILENAME		= 'D:\SQLData\Default\DBACentral_History_Data.ndf'
	,SIZE			= 1 GB
	,MAXSIZE		= UNLIMITED
	,FILEGROWTH		= 512 MB
)
LOG ON 
(
	name			= DBACentral_Log
	,FILENAME		= 'D:\SQLLogs\Default\DBACentral_Log.ldf'
	,SIZE			= 1 GB
	,MAXSIZE		= UNLIMITED
	,FILEGROWTH		= 512 MB
)
GO

USE [DBACentral]
ALTER DATABASE [DBACentral] SET SINGLE_USER WITH ROLLBACK IMMEDIATE

ALTER DATABASE [DBACentral] SET RECOVERY FULL

-- Automatic
ALTER DATABASE [DBACentral] SET AUTO_CLOSE						OFF
ALTER DATABASE [DBACentral] SET AUTO_CREATE_STATISTICS			ON
ALTER DATABASE [DBACentral] SET AUTO_SHRINK						OFF
ALTER DATABASE [DBACentral] SET AUTO_UPDATE_STATISTICS			ON
ALTER DATABASE [DBACentral] SET AUTO_UPDATE_STATISTICS_ASYNC	OFF
-- Cursor
ALTER DATABASE [DBACentral] SET CURSOR_CLOSE_ON_COMMIT			OFF
ALTER DATABASE [DBACentral] SET CURSOR_DEFAULT					LOCAL
-- Miscellaneous
ALTER DATABASE [DBACentral] SET ANSI_NULL_DEFAULT				OFF
ALTER DATABASE [DBACentral] SET ANSI_NULLS						OFF
ALTER DATABASE [DBACentral] SET ANSI_PADDING					OFF
ALTER DATABASE [DBACentral] SET ANSI_WARNINGS					OFF
ALTER DATABASE [DBACentral] SET ARITHABORT						ON
ALTER DATABASE [DBACentral] SET CONCAT_NULL_YIELDS_NULL			OFF
ALTER DATABASE [DBACentral] SET DB_CHAINING						OFF
ALTER DATABASE [DBACentral] SET DATE_CORRELATION_OPTIMIZATION	OFF
ALTER DATABASE [DBACentral] SET NUMERIC_ROUNDABORT				OFF
ALTER DATABASE [DBACentral] SET PARAMETERIZATION				SIMPLE
ALTER DATABASE [DBACentral] SET QUOTED_IDENTIFIER				OFF
ALTER DATABASE [DBACentral] SET RECURSIVE_TRIGGERS				OFF
ALTER DATABASE [DBACentral] SET TRUSTWORTHY						OFF
-- Recovery
ALTER DATABASE [DBACentral] SET PAGE_VERIFY						CHECKSUM
-- Service Broker
ALTER DATABASE [DBACentral] SET DISABLE_BROKER
-- State
ALTER DATABASE [DBACentral] SET READ_WRITE
ALTER DATABASE [DBACentral] SET MULTI_USER


DECLARE @Owner SYSNAME

SELECT @Owner = [name] 
FROM sys.server_principals
WHERE [sid] = 0x01

USE [DBACentral]

EXEC sp_changedbowner @Owner

EXEC sys.sp_addextendedproperty @name=N'Version', @value=N'1.0.0' 